### ISSUE TITLE
Does not work using jQuery 3.0.0 

### ISSUE THREAD

**Issue by Jivings** [mistic100/jQuery-QueryBuilder#308]
This is probably expected, but due to the `bower.json` the latest version of jQuery is pulled in as a dependency.

There may be more incompatibilities, but the first is caused by [extendext][2] on initialization of the plugin. Namely [this line][1], which always returns an empty `Object` for `filters`, instead of an `Array`.

[1]: https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/core.js#L9
[2]: https://github.com/mistic100/jQuery.extendext/issues/1

**Comment by mcantrell** [comment]
Confirmed broken for me in the same place. Results in the following error (for those Googling for an answer):

    TypeError: filters.forEach is not a function
        at QueryBuilder.checkFilters (query-builder.js:410:13)

This was the only lib I have with jQuery so a fresh build pulled in jQuery 3.0.0.  Explictly declaring my own jQuery version resolved the problem:

    "jquery": ">= 1.9.0 < 3.0.0"
